import type { Artist, CalendarEvent, Party, PartyApplicant, ChatRoom, ChatMessage, SeatSection, Seat, Notification } from '@/types';

export const mockArtists: Artist[] = [
  { id: '1', name: 'BTS', shortName: 'BTS', scheduleCount: 12, fanCount: 1250000 },
  { id: '2', name: 'BLACKPINK', shortName: 'BP', scheduleCount: 8, fanCount: 980000 },
  { id: '3', name: 'NewJeans', shortName: 'NJ', scheduleCount: 15, fanCount: 870000 },
  { id: '4', name: 'aespa', shortName: 'ae', scheduleCount: 10, fanCount: 650000 },
  { id: '5', name: 'IVE', shortName: 'IVE', scheduleCount: 9, fanCount: 720000 },
  { id: '6', name: 'Stray Kids', shortName: 'SKZ', scheduleCount: 11, fanCount: 890000 },
  { id: '7', name: 'SEVENTEEN', shortName: 'SVT', scheduleCount: 14, fanCount: 950000 },
  { id: '8', name: 'TWICE', shortName: 'TW', scheduleCount: 7, fanCount: 1100000 },
  { id: '9', name: 'NCT', shortName: 'NCT', scheduleCount: 18, fanCount: 780000 },
  { id: '10', name: 'Red Velvet', shortName: 'RV', scheduleCount: 6, fanCount: 560000 },
  { id: '11', name: 'EXO', shortName: 'EXO', scheduleCount: 5, fanCount: 920000 },
  { id: '12', name: 'LE SSERAFIM', shortName: 'LSF', scheduleCount: 8, fanCount: 480000 },
];

export const mockEvents: CalendarEvent[] = [
  // December 2025 Events - Early December (1-10)
  {
    id: 'dec-1',
    title: 'NCT DREAM 팬사인회',
    date: '2025-12-01',
    time: '15:00',
    type: 'fansign',
    artistId: '9',
    artistName: 'NCT',
    venue: '여의도 IFC몰',
    price: 55000,
    availableSeats: 120,
  },
  {
    id: 'dec-2',
    title: 'Red Velvet 음악방송 출연',
    date: '2025-12-02',
    time: '17:30',
    type: 'broadcast',
    artistId: '10',
    artistName: 'Red Velvet',
    venue: 'SBS 프리즘타워',
    price: 0,
    availableSeats: 180,
  },
  {
    id: 'dec-3',
    title: 'LE SSERAFIM FLAME RISES',
    date: '2025-12-03',
    time: '19:00',
    type: 'concert',
    artistId: '12',
    artistName: 'LE SSERAFIM',
    venue: '올림픽공원 올림픽홀',
    price: 125000,
    availableSeats: 2000,
  },
  {
    id: 'dec-4',
    title: 'EXO 카이 생일',
    date: '2025-12-04',
    time: '00:00',
    type: 'birthday',
    artistId: '11',
    artistName: 'EXO',
    venue: '',
  },
  {
    id: 'dec-5',
    title: 'TWICE 뮤직뱅크 출연',
    date: '2025-12-05',
    time: '17:00',
    type: 'broadcast',
    artistId: '8',
    artistName: 'TWICE',
    venue: 'KBS 홀',
    price: 0,
    availableSeats: 150,
  },
  {
    id: 'dec-6',
    title: 'aespa 단독 콘서트',
    date: '2025-12-06',
    time: '18:00',
    type: 'concert',
    artistId: '4',
    artistName: 'aespa',
    venue: '잠실실내체육관',
    price: 138000,
    availableSeats: 1200,
  },
  {
    id: 'dec-7',
    title: 'IVE 팬사인회',
    date: '2025-12-06',
    time: '14:00',
    type: 'fansign',
    artistId: '5',
    artistName: 'IVE',
    venue: '스타필드 하남',
    price: 52000,
    availableSeats: 100,
  },
  {
    id: 'dec-8',
    title: 'NewJeans 쇼챔피언 출연',
    date: '2025-12-07',
    time: '18:00',
    type: 'broadcast',
    artistId: '3',
    artistName: 'NewJeans',
    venue: 'MBC M 상암 스튜디오',
    price: 0,
    availableSeats: 160,
  },
  {
    id: 'dec-9',
    title: 'Stray Kids ROCK STAR 콘서트',
    date: '2025-12-07',
    time: '19:00',
    type: 'concert',
    artistId: '6',
    artistName: 'Stray Kids',
    venue: '고척스카이돔',
    price: 145000,
    availableSeats: 2500,
  },
  {
    id: 'dec-10',
    title: 'SEVENTEEN 팬사인회',
    date: '2025-12-08',
    time: '15:00',
    type: 'fansign',
    artistId: '7',
    artistName: 'SEVENTEEN',
    venue: '타임스퀘어 아트리움',
    price: 58000,
    availableSeats: 150,
  },
  {
    id: 'dec-11',
    title: 'BTS 진 생일',
    date: '2025-12-04',
    time: '00:00',
    type: 'birthday',
    artistId: '1',
    artistName: 'BTS',
    venue: '',
  },

  // December 2025 Events - Mid December (11-20) - 오늘(12/11) 전후
  {
    id: 'dec-12',
    title: 'NCT 127 인기가요 출연',
    date: '2025-12-11',
    time: '15:40',
    type: 'broadcast',
    artistId: '9',
    artistName: 'NCT',
    venue: 'SBS 목동 스튜디오',
    price: 0,
    availableSeats: 200,
  },
  {
    id: 'dec-13',
    title: 'BLACKPINK 로제 솔로 콘서트',
    date: '2025-12-11',
    time: '19:00',
    type: 'concert',
    artistId: '2',
    artistName: 'BLACKPINK',
    venue: '올림픽공원 KSPO DOME',
    price: 155000,
    availableSeats: 3000,
  },
  {
    id: 'dec-14',
    title: 'IVE 원영 생일',
    date: '2025-12-11',
    time: '00:00',
    type: 'birthday',
    artistId: '5',
    artistName: 'IVE',
    venue: '',
  },
  {
    id: 'dec-15',
    title: 'NewJeans 하니 생일',
    date: '2025-12-12',
    time: '00:00',
    type: 'birthday',
    artistId: '3',
    artistName: 'NewJeans',
    venue: '',
  },
  {
    id: 'dec-16',
    title: 'aespa 팬사인회',
    date: '2025-12-12',
    time: '14:00',
    type: 'fansign',
    artistId: '4',
    artistName: 'aespa',
    venue: '롯데월드몰 아트리움',
    price: 55000,
    availableSeats: 120,
  },
  {
    id: 'dec-17',
    title: 'Red Velvet 웬디 생일',
    date: '2025-12-12',
    time: '00:00',
    type: 'birthday',
    artistId: '10',
    artistName: 'Red Velvet',
    venue: '',
  },
  {
    id: 'dec-18',
    title: 'EXO 연말 콘서트',
    date: '2025-12-13',
    time: '18:00',
    type: 'concert',
    artistId: '11',
    artistName: 'EXO',
    venue: '잠실종합운동장',
    price: 160000,
    availableSeats: 5000,
  },
  {
    id: 'dec-19',
    title: 'TWICE 팬미팅',
    date: '2025-12-13',
    time: '15:00',
    type: 'fansign',
    artistId: '8',
    artistName: 'TWICE',
    venue: '코엑스 D홀',
    price: 65000,
    availableSeats: 300,
  },
  {
    id: 'dec-20',
    title: 'LE SSERAFIM 음악중심 출연',
    date: '2025-12-13',
    time: '15:30',
    type: 'broadcast',
    artistId: '12',
    artistName: 'LE SSERAFIM',
    venue: 'MBC 상암 스튜디오',
    price: 0,
    availableSeats: 180,
  },
  {
    id: 'dec-21',
    title: 'Stray Kids 팬사인회',
    date: '2025-12-14',
    time: '14:00',
    type: 'fansign',
    artistId: '6',
    artistName: 'Stray Kids',
    venue: '스타필드 고양',
    price: 60000,
    availableSeats: 150,
  },
  {
    id: '1',
    title: 'BTS WORLD TOUR 2025',
    date: '2025-12-15',
    time: '18:00',
    type: 'concert',
    artistId: '1',
    artistName: 'BTS',
    venue: '잠실종합운동장',
    price: 150000,
    availableSeats: 2500,
  },
  {
    id: 'dec-22',
    title: 'NewJeans 더 쇼 출연',
    date: '2025-12-15',
    time: '18:00',
    type: 'broadcast',
    artistId: '3',
    artistName: 'NewJeans',
    venue: 'SBS M 프리즘타워',
    price: 0,
    availableSeats: 140,
  },
  {
    id: 'dec-23',
    title: 'SEVENTEEN 민규 생일',
    date: '2025-12-16',
    time: '00:00',
    type: 'birthday',
    artistId: '7',
    artistName: 'SEVENTEEN',
    venue: '',
  },
  {
    id: 'dec-24',
    title: 'NCT DREAM 콘서트',
    date: '2025-12-16',
    time: '19:00',
    type: 'concert',
    artistId: '9',
    artistName: 'NCT',
    venue: '고척스카이돔',
    price: 140000,
    availableSeats: 2000,
  },
  {
    id: 'dec-25',
    title: 'IVE 음악방송 출연',
    date: '2025-12-17',
    time: '17:00',
    type: 'broadcast',
    artistId: '5',
    artistName: 'IVE',
    venue: 'KBS 홀',
    price: 0,
    availableSeats: 150,
  },
  {
    id: '2',
    title: 'BLACKPINK 팬사인회',
    date: '2025-12-18',
    time: '14:00',
    type: 'fansign',
    artistId: '2',
    artistName: 'BLACKPINK',
    venue: 'COEX 아트리움',
    price: 50000,
    availableSeats: 100,
  },
  {
    id: 'dec-26',
    title: 'aespa 뮤직뱅크 출연',
    date: '2025-12-19',
    time: '17:30',
    type: 'broadcast',
    artistId: '4',
    artistName: 'aespa',
    venue: 'KBS 홀',
    price: 0,
    availableSeats: 150,
  },
  {
    id: '3',
    title: 'NewJeans 음악방송 출연',
    date: '2025-12-20',
    time: '17:30',
    type: 'broadcast',
    artistId: '3',
    artistName: 'NewJeans',
    venue: 'MBC 일산스튜디오',
    price: 0,
    availableSeats: 200,
  },
  {
    id: 'dec-27',
    title: 'Red Velvet 단독 콘서트',
    date: '2025-12-20',
    time: '18:00',
    type: 'concert',
    artistId: '10',
    artistName: 'Red Velvet',
    venue: '올림픽공원 올림픽홀',
    price: 130000,
    availableSeats: 1500,
  },

  // December 2025 Events - Late December (21-31)
  {
    id: 'dec-28',
    title: 'SEVENTEEN 팬사인회',
    date: '2025-12-21',
    time: '14:00',
    type: 'fansign',
    artistId: '7',
    artistName: 'SEVENTEEN',
    venue: '현대백화점 판교',
    price: 60000,
    availableSeats: 120,
  },
  {
    id: '5',
    title: 'IVE THE FIRST FAN CONCERT',
    date: '2025-12-22',
    time: '19:00',
    type: 'concert',
    artistId: '5',
    artistName: 'IVE',
    venue: '올림픽공원 KSPO DOME',
    price: 130000,
    availableSeats: 1500,
  },
  {
    id: 'dec-29',
    title: 'LE SSERAFIM 팬미팅',
    date: '2025-12-22',
    time: '15:00',
    type: 'fansign',
    artistId: '12',
    artistName: 'LE SSERAFIM',
    venue: '코엑스 그랜드볼룸',
    price: 70000,
    availableSeats: 200,
  },
  {
    id: 'dec-30',
    title: 'NCT 127 인기가요 출연',
    date: '2025-12-23',
    time: '15:40',
    type: 'broadcast',
    artistId: '9',
    artistName: 'NCT',
    venue: 'SBS 목동 스튜디오',
    price: 0,
    availableSeats: 180,
  },
  {
    id: 'dec-31',
    title: 'BTS 크리스마스 팬미팅',
    date: '2025-12-24',
    time: '17:00',
    type: 'fansign',
    artistId: '1',
    artistName: 'BTS',
    venue: '그랜드 인터컨티넨탈 서울',
    price: 85000,
    availableSeats: 250,
  },
  {
    id: 'dec-32',
    title: 'NewJeans 크리스마스 콘서트',
    date: '2025-12-24',
    time: '19:00',
    type: 'concert',
    artistId: '3',
    artistName: 'NewJeans',
    venue: '올림픽공원 KSPO DOME',
    price: 145000,
    availableSeats: 3000,
  },
  {
    id: 'dec-33',
    title: 'aespa 지젤 생일',
    date: '2025-12-24',
    time: '00:00',
    type: 'birthday',
    artistId: '4',
    artistName: 'aespa',
    venue: '',
  },
  {
    id: '6',
    title: 'Stray Kids 팬미팅',
    date: '2025-12-25',
    time: '15:00',
    type: 'fansign',
    artistId: '6',
    artistName: 'Stray Kids',
    venue: '고척스카이돔',
    price: 80000,
    availableSeats: 500,
  },
  {
    id: 'dec-34',
    title: 'BLACKPINK 제니 생일',
    date: '2025-12-25',
    time: '00:00',
    type: 'birthday',
    artistId: '2',
    artistName: 'BLACKPINK',
    venue: '',
  },
  {
    id: 'dec-35',
    title: 'EXO 팬사인회',
    date: '2025-12-26',
    time: '14:00',
    type: 'fansign',
    artistId: '11',
    artistName: 'EXO',
    venue: '롯데백화점 본점',
    price: 70000,
    availableSeats: 100,
  },
  {
    id: 'dec-36',
    title: 'TWICE 연말 콘서트',
    date: '2025-12-27',
    time: '18:00',
    type: 'concert',
    artistId: '8',
    artistName: 'TWICE',
    venue: '잠실실내체육관',
    price: 135000,
    availableSeats: 1500,
  },
  {
    id: '7',
    title: 'SEVENTEEN FOLLOW 콘서트',
    date: '2025-12-28',
    time: '18:00',
    type: 'concert',
    artistId: '7',
    artistName: 'SEVENTEEN',
    venue: '잠실실내체육관',
    price: 140000,
    availableSeats: 1000,
  },
  {
    id: 'dec-37',
    title: 'aespa 연말 특집 방송',
    date: '2025-12-28',
    time: '20:00',
    type: 'broadcast',
    artistId: '4',
    artistName: 'aespa',
    venue: 'SBS 목동 스튜디오',
    price: 0,
    availableSeats: 200,
  },
  {
    id: 'dec-38',
    title: 'IVE 연말 팬미팅',
    date: '2025-12-29',
    time: '15:00',
    type: 'fansign',
    artistId: '5',
    artistName: 'IVE',
    venue: '코엑스 D홀',
    price: 68000,
    availableSeats: 250,
  },
  {
    id: 'dec-39',
    title: 'BTS 뷔 생일',
    date: '2025-12-30',
    time: '00:00',
    type: 'birthday',
    artistId: '1',
    artistName: 'BTS',
    venue: '',
  },
  {
    id: 'dec-40',
    title: 'Stray Kids 연말 콘서트',
    date: '2025-12-30',
    time: '18:00',
    type: 'concert',
    artistId: '6',
    artistName: 'Stray Kids',
    venue: '고척스카이돔',
    price: 148000,
    availableSeats: 2500,
  },
  {
    id: 'dec-41',
    title: 'NewJeans 연말 특집 방송',
    date: '2025-12-31',
    time: '20:00',
    type: 'broadcast',
    artistId: '3',
    artistName: 'NewJeans',
    venue: 'MBC 상암 스튜디오',
    price: 0,
    availableSeats: 200,
  },
  {
    id: '8',
    title: 'TWICE 연말 특집 방송',
    date: '2025-12-31',
    time: '22:00',
    type: 'broadcast',
    artistId: '8',
    artistName: 'TWICE',
    venue: 'KBS 여의도홀',
    price: 0,
    availableSeats: 150,
  },
  {
    id: 'dec-42',
    title: 'LE SSERAFIM 연말 콘서트',
    date: '2025-12-31',
    time: '18:00',
    type: 'concert',
    artistId: '12',
    artistName: 'LE SSERAFIM',
    venue: '올림픽공원 올림픽홀',
    price: 130000,
    availableSeats: 1800,
  },

  // January 2025 Events
  {
    id: '4',
    title: 'aespa WINTER 생일',
    date: '2025-01-01',
    time: '00:00',
    type: 'birthday',
    artistId: '4',
    artistName: 'aespa',
    venue: '',
  },
  {
    id: '9',
    title: 'BTS 신년 팬미팅',
    date: '2025-01-05',
    time: '16:00',
    type: 'fansign',
    artistId: '1',
    artistName: 'BTS',
    venue: '코엑스 컨벤션홀',
    price: 70000,
    availableSeats: 800,
  },
  {
    id: '10',
    title: 'NewJeans 쇼케이스',
    date: '2025-01-10',
    time: '19:00',
    type: 'concert',
    artistId: '3',
    artistName: 'NewJeans',
    venue: '블루스퀘어 마스터카드홀',
    price: 110000,
    availableSeats: 1200,
  },
  {
    id: '11',
    title: 'aespa 뮤직뱅크 출연',
    date: '2025-01-12',
    time: '17:00',
    type: 'broadcast',
    artistId: '4',
    artistName: 'aespa',
    venue: 'KBS 홀',
    price: 0,
    availableSeats: 150,
  },
  {
    id: '12',
    title: 'SEVENTEEN 팬사인회',
    date: '2025-01-15',
    time: '14:00',
    type: 'fansign',
    artistId: '7',
    artistName: 'SEVENTEEN',
    venue: '롯데월드몰 아트리움',
    price: 60000,
    availableSeats: 200,
  },
  {
    id: '13',
    title: 'ITZY SHOWCASE',
    date: '2025-01-18',
    time: '20:00',
    type: 'concert',
    artistId: '12',
    artistName: 'LE SSERAFIM',
    venue: '예스24 라이브홀',
    price: 95000,
    availableSeats: 900,
  },
  {
    id: '14',
    title: 'Stray Kids 음악중심 출연',
    date: '2025-01-20',
    time: '15:30',
    type: 'broadcast',
    artistId: '6',
    artistName: 'Stray Kids',
    venue: 'MBC 상암 스튜디오',
    price: 0,
    availableSeats: 180,
  },
  {
    id: '15',
    title: 'BTS RM 생일',
    date: '2025-01-12',
    time: '00:00',
    type: 'birthday',
    artistId: '1',
    artistName: 'BTS',
    venue: '',
  },

  // February 2025 Events
  {
    id: '16',
    title: 'NewJeans 발렌타인 콘서트',
    date: '2025-02-14',
    time: '18:00',
    type: 'concert',
    artistId: '3',
    artistName: 'NewJeans',
    venue: '올림픽공원 올림픽홀',
    price: 125000,
    availableSeats: 2000,
  },
  {
    id: '17',
    title: 'aespa 팬사인회',
    date: '2025-02-05',
    time: '15:00',
    type: 'fansign',
    artistId: '4',
    artistName: 'aespa',
    venue: '스타필드 고양',
    price: 55000,
    availableSeats: 150,
  },
  {
    id: '18',
    title: 'SEVENTEEN 인기가요 출연',
    date: '2025-02-09',
    time: '15:40',
    type: 'broadcast',
    artistId: '7',
    artistName: 'SEVENTEEN',
    venue: 'SBS 프리즘타워',
    price: 0,
    availableSeats: 200,
  },
  {
    id: '19',
    title: 'Stray Kids MANIAC TOUR',
    date: '2025-02-20',
    time: '19:00',
    type: 'concert',
    artistId: '6',
    artistName: 'Stray Kids',
    venue: 'KSPO DOME',
    price: 145000,
    availableSeats: 1800,
  },
  {
    id: '20',
    title: 'BTS 팬사인회',
    date: '2025-02-22',
    time: '14:00',
    type: 'fansign',
    artistId: '1',
    artistName: 'BTS',
    venue: '여의도 IFC몰',
    price: 75000,
    availableSeats: 120,
  },
  {
    id: '21',
    title: 'aespa 쇼챔피언 출연',
    date: '2025-02-26',
    time: '18:00',
    type: 'broadcast',
    artistId: '4',
    artistName: 'aespa',
    venue: 'MBC M 상암 스튜디오',
    price: 0,
    availableSeats: 160,
  },

  // March 2025 Events
  {
    id: '22',
    title: 'NewJeans 봄맞이 팬미팅',
    date: '2025-03-01',
    time: '17:00',
    type: 'fansign',
    artistId: '3',
    artistName: 'NewJeans',
    venue: '잠실 롯데월드몰',
    price: 65000,
    availableSeats: 300,
  },
  {
    id: '23',
    title: 'SEVENTEEN WORLD TOUR',
    date: '2025-03-08',
    time: '18:30',
    type: 'concert',
    artistId: '7',
    artistName: 'SEVENTEEN',
    venue: '고척스카이돔',
    price: 155000,
    availableSeats: 3000,
  },
  {
    id: '24',
    title: 'Stray Kids 더 쇼 출연',
    date: '2025-03-11',
    time: '18:00',
    type: 'broadcast',
    artistId: '6',
    artistName: 'Stray Kids',
    venue: 'SBS M 프리즘타워',
    price: 0,
    availableSeats: 140,
  },
  {
    id: '25',
    title: 'aespa SYNK TOUR',
    date: '2025-03-15',
    time: '19:00',
    type: 'concert',
    artistId: '4',
    artistName: 'aespa',
    venue: '잠실실내체육관',
    price: 135000,
    availableSeats: 1500,
  },
  {
    id: '26',
    title: 'BTS 쇼케이스',
    date: '2025-03-20',
    time: '19:30',
    type: 'concert',
    artistId: '1',
    artistName: 'BTS',
    venue: '블루스퀘어 아이마켓홀',
    price: 160000,
    availableSeats: 1100,
  },
  {
    id: '27',
    title: 'NewJeans 팬사인회',
    date: '2025-03-25',
    time: '14:30',
    type: 'fansign',
    artistId: '3',
    artistName: 'NewJeans',
    venue: '메가박스 코엑스',
    price: 58000,
    availableSeats: 180,
  },
  {
    id: '28',
    title: 'SEVENTEEN HOSHI 생일',
    date: '2025-03-15',
    time: '00:00',
    type: 'birthday',
    artistId: '7',
    artistName: 'SEVENTEEN',
    venue: '',
  },
];

export const mockParties: Party[] = [
  // BTS Event Parties
  {
    id: 'party-1',
    title: 'BTS 콘서트 같이 가실 분!',
    eventId: '1',
    eventName: 'BTS WORLD TOUR 2025',
    eventDate: '2025-12-15',
    hostId: 'user-1',
    hostName: '아미팬',
    type: 'departure',
    departure: '서울역',
    arrival: '잠실종합운동장',
    departureTime: '16:00',
    maxMembers: 4,
    currentMembers: 2,
    status: 'recruiting',
    description: '서울역에서 출발합니다. 함께 가요!',
    createdAt: '2025-12-10T10:00:00Z',
  },
  {
    id: 'party-2',
    title: 'BTS 콘서트 후 귀가',
    eventId: '1',
    eventName: 'BTS WORLD TOUR 2025',
    eventDate: '2025-12-15',
    hostId: 'user-2',
    hostName: '방탄소녀단',
    type: 'return',
    departure: '잠실종합운동장',
    arrival: '강남역',
    departureTime: '22:00',
    maxMembers: 3,
    currentMembers: 3,
    status: 'confirmed',
    description: '공연 끝나고 강남역까지 함께 가요~',
    createdAt: '2025-12-10T11:00:00Z',
  },
  {
    id: 'party-4',
    title: 'BTS 신년 팬미팅 동행',
    eventId: '9',
    eventName: 'BTS 신년 팬미팅',
    eventDate: '2026-01-01',
    hostId: 'user-4',
    hostName: '보라해',
    type: 'departure',
    departure: '삼성역',
    arrival: '코엑스 컨벤션홀',
    departureTime: '14:30',
    maxMembers: 4,
    currentMembers: 4,
    status: 'closed',
    description: '코엑스 근처에서 출발해요',
    createdAt: '2025-12-11T09:00:00Z',
  },

  // BLACKPINK Event Parties
  {
    id: 'party-3',
    title: 'BLACKPINK 팬사인회 동행',
    eventId: '2',
    eventName: 'BLACKPINK 팬사인회',
    eventDate: '2025-12-18',
    hostId: 'user-3',
    hostName: '블링크',
    type: 'departure',
    departure: '홍대입구역',
    arrival: 'COEX',
    departureTime: '12:00',
    maxMembers: 5,
    currentMembers: 3,
    status: 'recruiting',
    description: '점심 먹고 같이 가요!',
    createdAt: '2025-12-10T09:00:00Z',
  },
  {
    id: 'party-5',
    title: 'BLACKPINK 팬사인회 귀가',
    eventId: '2',
    eventName: 'BLACKPINK 팬사인회',
    eventDate: '2025-12-18',
    hostId: 'user-5',
    hostName: '핑크팬',
    type: 'return',
    departure: 'COEX',
    arrival: '신논현역',
    departureTime: '17:00',
    maxMembers: 3,
    currentMembers: 2,
    status: 'recruiting',
    description: '팬사인회 끝나고 신논현역까지 가요',
    createdAt: '2025-12-11T10:30:00Z',
  },

  // NewJeans Event Parties
  {
    id: 'party-6',
    title: 'NewJeans 음악방송 같이 보러 가요',
    eventId: '3',
    eventName: 'NewJeans 음악방송 출연',
    eventDate: '2025-12-20',
    hostId: 'user-6',
    hostName: '토끼팬',
    type: 'departure',
    departure: '디지털미디어시티역',
    arrival: 'MBC 일산스튜디오',
    departureTime: '15:30',
    maxMembers: 4,
    currentMembers: 1,
    status: 'recruiting',
    description: '첫 방문이라 긴장돼요! 함께 가요~',
    createdAt: '2025-12-11T08:00:00Z',
  },
  {
    id: 'party-7',
    title: 'NewJeans 쇼케이스 출발',
    eventId: '10',
    eventName: 'NewJeans 쇼케이스',
    eventDate: '2025-12-22',
    hostId: 'user-7',
    hostName: '뉴진스짱',
    type: 'departure',
    departure: '한양대역',
    arrival: '블루스퀘어 마스터카드홀',
    departureTime: '17:00',
    maxMembers: 5,
    currentMembers: 3,
    status: 'recruiting',
    description: '한양대역 2번 출구에서 만나요',
    createdAt: '2025-12-12T11:00:00Z',
  },
  {
    id: 'party-8',
    title: 'NewJeans 발렌타인 콘서트 동행',
    eventId: '16',
    eventName: 'NewJeans 발렌타인 콘서트',
    eventDate: '2026-02-14',
    hostId: 'user-1',
    hostName: '아미팬',
    type: 'departure',
    departure: '잠실역',
    arrival: '올림픽공원 올림픽홀',
    departureTime: '16:00',
    maxMembers: 4,
    currentMembers: 2,
    status: 'recruiting',
    description: '발렌타인 데이에 함께 가요!',
    createdAt: '2025-12-13T09:30:00Z',
  },

  // aespa Event Parties
  {
    id: 'party-9',
    title: 'aespa 뮤직뱅크 같이 가요',
    eventId: '11',
    eventName: 'aespa 뮤직뱅크 출연',
    eventDate: '2025-12-27',
    hostId: 'user-8',
    hostName: '마이',
    type: 'departure',
    departure: '여의도역',
    arrival: 'KBS 홀',
    departureTime: '15:30',
    maxMembers: 3,
    currentMembers: 2,
    status: 'recruiting',
    description: 'KBS 앞에서 만나요',
    createdAt: '2025-12-12T10:00:00Z',
  },
  {
    id: 'party-10',
    title: 'aespa 팬사인회 동행',
    eventId: '17',
    eventName: 'aespa 팬사인회',
    eventDate: '2025-12-30',
    hostId: 'user-9',
    hostName: '카리나팬',
    type: 'departure',
    departure: '삼송역',
    arrival: '스타필드 고양',
    departureTime: '13:00',
    maxMembers: 4,
    currentMembers: 4,
    status: 'confirmed',
    description: '스타필드 고양 팬사인회 가실 분~',
    createdAt: '2025-12-13T08:00:00Z',
  },
  {
    id: 'party-11',
    title: 'aespa SYNK TOUR 같이 가요',
    eventId: '25',
    eventName: 'aespa SYNK TOUR',
    eventDate: '2026-01-10',
    hostId: 'user-2',
    hostName: '방탄소녀단',
    type: 'departure',
    departure: '종합운동장역',
    arrival: '잠실실내체육관',
    departureTime: '17:00',
    maxMembers: 5,
    currentMembers: 1,
    status: 'recruiting',
    description: '잠실 콘서트 같이 가실 분 모집해요',
    createdAt: '2025-12-14T09:00:00Z',
  },

  // SEVENTEEN Event Parties
  {
    id: 'party-12',
    title: 'SEVENTEEN 팬사인회 함께 가요',
    eventId: '12',
    eventName: 'SEVENTEEN 팬사인회',
    eventDate: '2025-12-28',
    hostId: 'user-10',
    hostName: '캐럿',
    type: 'departure',
    departure: '잠실역',
    arrival: '롯데월드몰 아트리움',
    departureTime: '12:30',
    maxMembers: 3,
    currentMembers: 2,
    status: 'recruiting',
    description: '잠실역에서 출발합니다',
    createdAt: '2025-12-13T10:00:00Z',
  },
  {
    id: 'party-13',
    title: 'SEVENTEEN 인기가요 출연 관람',
    eventId: '18',
    eventName: 'SEVENTEEN 인기가요 출연',
    eventDate: '2026-01-05',
    hostId: 'user-11',
    hostName: '세봉이',
    type: 'departure',
    departure: '목동역',
    arrival: 'SBS 프리즘타워',
    departureTime: '14:00',
    maxMembers: 4,
    currentMembers: 3,
    status: 'recruiting',
    description: 'SBS 프리즘타워 앞에서 만나요',
    createdAt: '2025-12-14T08:30:00Z',
  },
  {
    id: 'party-14',
    title: 'SEVENTEEN WORLD TOUR 동행',
    eventId: '23',
    eventName: 'SEVENTEEN WORLD TOUR',
    eventDate: '2026-02-01',
    hostId: 'user-3',
    hostName: '블링크',
    type: 'departure',
    departure: '구로디지털단지역',
    arrival: '고척스카이돔',
    departureTime: '16:00',
    maxMembers: 5,
    currentMembers: 5,
    status: 'confirmed',
    description: '고척 콘서트 가시는 분들 모집합니다',
    createdAt: '2025-12-15T09:00:00Z',
  },
  {
    id: 'party-15',
    title: 'SEVENTEEN WORLD TOUR 귀가',
    eventId: '23',
    eventName: 'SEVENTEEN WORLD TOUR',
    eventDate: '2026-02-01',
    hostId: 'user-12',
    hostName: '호시팬',
    type: 'return',
    departure: '고척스카이돔',
    arrival: '영등포역',
    departureTime: '22:00',
    maxMembers: 4,
    currentMembers: 2,
    status: 'recruiting',
    description: '콘서트 끝나고 영등포역까지 함께 가요',
    createdAt: '2025-12-15T10:00:00Z',
  },

  // Stray Kids Event Parties
  {
    id: 'party-16',
    title: 'Stray Kids 팬미팅 출발',
    eventId: '6',
    eventName: 'Stray Kids 팬미팅',
    eventDate: '2025-12-25',
    hostId: 'user-13',
    hostName: '스테이',
    type: 'departure',
    departure: '구로디지털단지역',
    arrival: '고척스카이돔',
    departureTime: '13:00',
    maxMembers: 4,
    currentMembers: 1,
    status: 'recruiting',
    description: '고척스카이돔 팬미팅 같이 가요',
    createdAt: '2025-12-15T11:00:00Z',
  },
  {
    id: 'party-17',
    title: 'Stray Kids 음악중심 관람',
    eventId: '14',
    eventName: 'Stray Kids 음악중심 출연',
    hostId: 'user-14',
    hostName: '방찬이',
    type: 'departure',
    departure: '디지털미디어시티역',
    arrival: 'MBC 상암 스튜디오',
    departureTime: '14:00',
    maxMembers: 3,
    currentMembers: 3,
    status: 'confirmed',
    description: 'MBC 상암 스튜디오 관람 가실 분',
    createdAt: '2025-12-16T09:00:00Z',
  },
  {
    id: 'party-18',
    title: 'Stray Kids MANIAC TOUR 동행',
    eventId: '19',
    eventName: 'Stray Kids MANIAC TOUR',
    hostId: 'user-15',
    hostName: '현진팬',
    type: 'departure',
    departure: '잠실역',
    arrival: 'KSPO DOME',
    departureTime: '17:00',
    maxMembers: 5,
    currentMembers: 2,
    status: 'recruiting',
    description: 'KSPO DOME 콘서트 함께 가요!',
    createdAt: '2025-12-16T10:00:00Z',
  },
  {
    id: 'party-19',
    title: 'Stray Kids MANIAC TOUR 귀가',
    eventId: '19',
    eventName: 'Stray Kids MANIAC TOUR',
    hostId: 'user-4',
    hostName: '보라해',
    type: 'return',
    departure: 'KSPO DOME',
    arrival: '건대입구역',
    departureTime: '22:00',
    maxMembers: 3,
    currentMembers: 1,
    status: 'recruiting',
    description: '공연 끝나고 건대입구역으로 이동',
    createdAt: '2025-12-16T11:00:00Z',
  },
];

export const mockChatRooms: ChatRoom[] = [
  {
    id: 'chat-1',
    partyId: 'party-1',
    title: 'BTS 콘서트 같이 가실 분!',
    participants: [
      { id: 'user-1', name: '아미팬', isOwner: true, isOnline: true },
      { id: 'user-4', name: '보라해', isOwner: false, isOnline: true },
    ],
    isOwner: true,
    lastMessage: '안녕하세요! 같이 가요~',
    lastMessageTime: '2025-12-10T12:30:00Z',
    unreadCount: 2,
  },
  {
    id: 'chat-2',
    partyId: 'party-3',
    title: 'BLACKPINK 팬사인회 동행',
    participants: [
      { id: 'user-3', name: '블링크', isOwner: true, isOnline: false },
      { id: 'user-1', name: '아미팬', isOwner: false, isOnline: true },
      { id: 'user-5', name: '핑크팬', isOwner: false, isOnline: true },
    ],
    isOwner: false,
    lastMessage: '몇 시에 만날까요?',
    lastMessageTime: '2025-12-10T11:45:00Z',
    unreadCount: 0,
  },
  {
    id: 'chat-3',
    partyId: 'party-6',
    title: 'NewJeans 음악방송 같이 보러 가요',
    participants: [
      { id: 'user-6', name: '토끼팬', isOwner: true, isOnline: true },
      { id: 'user-19', name: '민지팬', isOwner: false, isOnline: false },
    ],
    isOwner: false,
    lastMessage: '음악방송 처음인데 뭐 준비해야 할까요?',
    lastMessageTime: '2025-12-11T09:30:00Z',
    unreadCount: 5,
  },
  {
    id: 'chat-4',
    partyId: 'party-7',
    title: 'NewJeans 쇼케이스 출발',
    participants: [
      { id: 'user-7', name: '뉴진스짱', isOwner: true, isOnline: true },
      { id: 'user-21', name: '혜인짱', isOwner: false, isOnline: true },
      { id: 'user-22', name: '다니엘팬', isOwner: false, isOnline: false },
    ],
    isOwner: false,
    lastMessage: '한양대역 2번 출구에서 5시에 만나요!',
    lastMessageTime: '2025-12-12T14:00:00Z',
    unreadCount: 3,
  },
  {
    id: 'chat-5',
    partyId: 'party-10',
    title: 'aespa 팬사인회 동행',
    participants: [
      { id: 'user-9', name: '카리나팬', isOwner: true, isOnline: true },
      { id: 'user-24', name: '윈터팬', isOwner: false, isOnline: true },
      { id: 'user-1', name: '아미팬', isOwner: false, isOnline: true },
      { id: 'user-25', name: '닝닝팬', isOwner: false, isOnline: false },
    ],
    isOwner: false,
    lastMessage: '스타필드 고양 맛집 추천해주세요~',
    lastMessageTime: '2025-12-13T10:15:00Z',
    unreadCount: 1,
  },
  {
    id: 'chat-6',
    partyId: 'party-12',
    title: 'SEVENTEEN 팬사인회 함께 가요',
    participants: [
      { id: 'user-10', name: '캐럿', isOwner: true, isOnline: false },
      { id: 'user-26', name: '에스쿱스팬', isOwner: false, isOnline: true },
    ],
    isOwner: true,
    lastMessage: '팬사인회 당첨되셨어요?',
    lastMessageTime: '2025-12-13T11:30:00Z',
    unreadCount: 0,
  },
  {
    id: 'chat-7',
    partyId: 'party-14',
    title: 'SEVENTEEN WORLD TOUR 동행',
    participants: [
      { id: 'user-3', name: '블링크', isOwner: true, isOnline: true },
      { id: 'user-27', name: '정한팬', isOwner: false, isOnline: true },
      { id: 'user-28', name: '조슈아팬', isOwner: false, isOnline: true },
      { id: 'user-29', name: '디노팬', isOwner: false, isOnline: false },
      { id: 'user-30', name: '버논팬', isOwner: false, isOnline: true },
    ],
    isOwner: false,
    lastMessage: '고척스카이돔 처음 가보는데 자리 어때요?',
    lastMessageTime: '2025-12-15T09:45:00Z',
    unreadCount: 8,
  },
  {
    id: 'chat-8',
    partyId: 'party-17',
    title: 'Stray Kids 음악중심 관람',
    participants: [
      { id: 'user-14', name: '방찬이', isOwner: true, isOnline: true },
      { id: 'user-31', name: '아이엔팬', isOwner: false, isOnline: false },
      { id: 'user-32', name: '승민팬', isOwner: false, isOnline: true },
    ],
    isOwner: false,
    lastMessage: '응원봉 꼭 챙겨오세요!',
    lastMessageTime: '2025-12-16T08:00:00Z',
    unreadCount: 0,
  },
  {
    id: 'chat-9',
    partyId: 'party-18',
    title: 'Stray Kids MANIAC TOUR 동행',
    participants: [
      { id: 'user-15', name: '현진팬', isOwner: true, isOnline: true },
      { id: 'user-31', name: '아이엔팬', isOwner: false, isOnline: true },
    ],
    isOwner: false,
    lastMessage: 'KSPO DOME 좌석 정보 공유해드릴게요',
    lastMessageTime: '2025-12-16T11:30:00Z',
    unreadCount: 4,
  },
  {
    id: 'chat-10',
    partyId: 'party-2',
    title: 'BTS 콘서트 후 귀가',
    participants: [
      { id: 'user-2', name: '방탄소녀단', isOwner: true, isOnline: true },
      { id: 'user-4', name: '보라해', isOwner: false, isOnline: true },
      { id: 'user-16', name: '아미러버', isOwner: false, isOnline: false },
    ],
    isOwner: false,
    lastMessage: '콘서트 끝나고 강남역까지 같이 가요~',
    lastMessageTime: '2025-12-10T13:00:00Z',
    unreadCount: 0,
  },
  {
    id: 'chat-11',
    partyId: 'party-8',
    title: 'NewJeans 발렌타인 콘서트 동행',
    participants: [
      { id: 'user-1', name: '아미팬', isOwner: true, isOnline: true },
      { id: 'user-23', name: '버니즈', isOwner: false, isOnline: true },
    ],
    isOwner: true,
    lastMessage: '발렌타인 데이 콘서트 너무 설레요!',
    lastMessageTime: '2025-12-13T15:20:00Z',
    unreadCount: 1,
  },
  {
    id: 'chat-12',
    partyId: 'party-11',
    title: 'aespa SYNK TOUR 같이 가요',
    participants: [
      { id: 'user-2', name: '방탄소녀단', isOwner: true, isOnline: false },
      { id: 'user-25', name: '닝닝팬', isOwner: false, isOnline: true },
    ],
    isOwner: false,
    lastMessage: '잠실 콘서트 좌석 어디가 좋을까요?',
    lastMessageTime: '2025-12-14T16:40:00Z',
    unreadCount: 2,
  },
];

export const mockChatMessages: Record<string, ChatMessage[]> = {
  'chat-1': [
    {
      id: 'msg-1',
      roomId: 'chat-1',
      senderId: 'user-1',
      senderName: '아미팬',
      content: '안녕하세요! 파티에 참여해주셔서 감사합니다 😊',
      timestamp: '2025-12-10T12:00:00Z',
    },
    {
      id: 'msg-2',
      roomId: 'chat-1',
      senderId: 'user-4',
      senderName: '보라해',
      content: '안녕하세요! 같이 가요~',
      timestamp: '2025-12-10T12:30:00Z',
    },
  ],
  'chat-2': [
    {
      id: 'msg-3',
      roomId: 'chat-2',
      senderId: 'user-3',
      senderName: '블링크',
      content: '환영합니다! 점심 메뉴 추천해주세요~',
      timestamp: '2025-12-10T10:00:00Z',
    },
    {
      id: 'msg-4',
      roomId: 'chat-2',
      senderId: 'user-5',
      senderName: '핑크팬',
      content: '저는 파스타 어떨까요?',
      timestamp: '2025-12-10T10:30:00Z',
    },
    {
      id: 'msg-5',
      roomId: 'chat-2',
      senderId: 'user-1',
      senderName: '아미팬',
      content: '몇 시에 만날까요?',
      timestamp: '2025-12-10T11:45:00Z',
    },
  ],
  'chat-3': [
    {
      id: 'msg-6',
      roomId: 'chat-3',
      senderId: 'user-6',
      senderName: '토끼팬',
      content: '뉴진스 음악방송 처음 가보시나요?',
      timestamp: '2025-12-11T09:00:00Z',
    },
    {
      id: 'msg-7',
      roomId: 'chat-3',
      senderId: 'user-19',
      senderName: '민지팬',
      content: '네! 처음이에요. 응원봉 꼭 가져가야 하나요?',
      timestamp: '2025-12-11T09:15:00Z',
    },
    {
      id: 'msg-8',
      roomId: 'chat-3',
      senderId: 'user-6',
      senderName: '토끼팬',
      content: '응원봉 있으면 좋아요! 버니즈봉 예쁘더라구요 ✨',
      timestamp: '2025-12-11T09:20:00Z',
    },
    {
      id: 'msg-9',
      roomId: 'chat-3',
      senderId: 'user-19',
      senderName: '민지팬',
      content: '음악방송 처음인데 뭐 준비해야 할까요?',
      timestamp: '2025-12-11T09:30:00Z',
    },
  ],
  'chat-4': [
    {
      id: 'msg-10',
      roomId: 'chat-4',
      senderId: 'user-7',
      senderName: '뉴진스짱',
      content: '쇼케이스 기대되시죠? 😆',
      timestamp: '2025-12-12T13:00:00Z',
    },
    {
      id: 'msg-11',
      roomId: 'chat-4',
      senderId: 'user-21',
      senderName: '혜인짱',
      content: '너무너무 기대돼요! 신곡 무대 볼 생각에 설레요',
      timestamp: '2025-12-12T13:15:00Z',
    },
    {
      id: 'msg-12',
      roomId: 'chat-4',
      senderId: 'user-22',
      senderName: '다니엘팬',
      content: '혹시 포토카드 교환하실 분 계신가요?',
      timestamp: '2025-12-12T13:30:00Z',
    },
    {
      id: 'msg-13',
      roomId: 'chat-4',
      senderId: 'user-7',
      senderName: '뉴진스짱',
      content: '한양대역 2번 출구에서 5시에 만나요!',
      timestamp: '2025-12-12T14:00:00Z',
    },
  ],
  'chat-5': [
    {
      id: 'msg-14',
      roomId: 'chat-5',
      senderId: 'user-9',
      senderName: '카리나팬',
      content: '에스파 팬사인회 당첨되신 분들 축하드려요! 🎉',
      timestamp: '2025-12-13T09:00:00Z',
    },
    {
      id: 'msg-15',
      roomId: 'chat-5',
      senderId: 'user-24',
      senderName: '윈터팬',
      content: '감사합니다! 첫 팬사인회라 긴장되네요',
      timestamp: '2025-12-13T09:30:00Z',
    },
    {
      id: 'msg-16',
      roomId: 'chat-5',
      senderId: 'user-1',
      senderName: '아미팬',
      content: '저도 처음인데 뭐 준비해야 할까요?',
      timestamp: '2025-12-13T09:45:00Z',
    },
    {
      id: 'msg-17',
      roomId: 'chat-5',
      senderId: 'user-25',
      senderName: '닝닝팬',
      content: '앨범이랑 포스트잇 준비하면 좋아요!',
      timestamp: '2025-12-13T10:00:00Z',
    },
    {
      id: 'msg-18',
      roomId: 'chat-5',
      senderId: 'user-9',
      senderName: '카리나팬',
      content: '스타필드 고양 맛집 추천해주세요~',
      timestamp: '2025-12-13T10:15:00Z',
    },
  ],
  'chat-6': [
    {
      id: 'msg-19',
      roomId: 'chat-6',
      senderId: 'user-10',
      senderName: '캐럿',
      content: '세븐틴 팬사인회 같이 가실 분 환영해요!',
      timestamp: '2025-12-13T11:00:00Z',
    },
    {
      id: 'msg-20',
      roomId: 'chat-6',
      senderId: 'user-26',
      senderName: '에스쿱스팬',
      content: '팬사인회 당첨되셨어요?',
      timestamp: '2025-12-13T11:30:00Z',
    },
  ],
  'chat-7': [
    {
      id: 'msg-21',
      roomId: 'chat-7',
      senderId: 'user-3',
      senderName: '블링크',
      content: '세븐틴 월드투어 드디어 가네요! 🎵',
      timestamp: '2025-12-15T08:00:00Z',
    },
    {
      id: 'msg-22',
      roomId: 'chat-7',
      senderId: 'user-27',
      senderName: '정한팬',
      content: '저도 너무 기대돼요! 정한이 볼 생각에 설레요',
      timestamp: '2025-12-15T08:30:00Z',
    },
    {
      id: 'msg-23',
      roomId: 'chat-7',
      senderId: 'user-28',
      senderName: '조슈아팬',
      content: '슈아 무대 진짜 기대됩니다',
      timestamp: '2025-12-15T09:00:00Z',
    },
    {
      id: 'msg-24',
      roomId: 'chat-7',
      senderId: 'user-29',
      senderName: '디노팬',
      content: '막내라인 무대도 기대돼요!',
      timestamp: '2025-12-15T09:15:00Z',
    },
    {
      id: 'msg-25',
      roomId: 'chat-7',
      senderId: 'user-30',
      senderName: '버논팬',
      content: '고척스카이돔 처음 가보는데 자리 어때요?',
      timestamp: '2025-12-15T09:45:00Z',
    },
  ],
  'chat-8': [
    {
      id: 'msg-26',
      roomId: 'chat-8',
      senderId: 'user-14',
      senderName: '방찬이',
      content: '스키즈 음악중심 관람 같이 가요!',
      timestamp: '2025-12-16T07:00:00Z',
    },
    {
      id: 'msg-27',
      roomId: 'chat-8',
      senderId: 'user-31',
      senderName: '아이엔팬',
      content: '아이엔 직캠 찍을 거예요!',
      timestamp: '2025-12-16T07:30:00Z',
    },
    {
      id: 'msg-28',
      roomId: 'chat-8',
      senderId: 'user-14',
      senderName: '방찬이',
      content: '응원봉 꼭 챙겨오세요!',
      timestamp: '2025-12-16T08:00:00Z',
    },
  ],
  'chat-9': [
    {
      id: 'msg-29',
      roomId: 'chat-9',
      senderId: 'user-15',
      senderName: '현진팬',
      content: 'MANIAC TOUR 드디어 가네요!',
      timestamp: '2025-12-16T10:00:00Z',
    },
    {
      id: 'msg-30',
      roomId: 'chat-9',
      senderId: 'user-31',
      senderName: '아이엔팬',
      content: '저도 같이 가요! 현진이 무대 기대돼요',
      timestamp: '2025-12-16T10:30:00Z',
    },
    {
      id: 'msg-31',
      roomId: 'chat-9',
      senderId: 'user-15',
      senderName: '현진팬',
      content: '좌석이 어디예요?',
      timestamp: '2025-12-16T11:00:00Z',
    },
    {
      id: 'msg-32',
      roomId: 'chat-9',
      senderId: 'user-31',
      senderName: '아이엔팬',
      content: 'KSPO DOME 좌석 정보 공유해드릴게요',
      timestamp: '2025-12-16T11:30:00Z',
    },
  ],
  'chat-10': [
    {
      id: 'msg-33',
      roomId: 'chat-10',
      senderId: 'user-2',
      senderName: '방탄소녀단',
      content: 'BTS 콘서트 끝나고 귀가 같이 하실 분!',
      timestamp: '2025-12-10T12:00:00Z',
    },
    {
      id: 'msg-34',
      roomId: 'chat-10',
      senderId: 'user-4',
      senderName: '보라해',
      content: '저도 강남역 방향이에요!',
      timestamp: '2025-12-10T12:30:00Z',
    },
    {
      id: 'msg-35',
      roomId: 'chat-10',
      senderId: 'user-16',
      senderName: '아미러버',
      content: '콘서트 끝나고 강남역까지 같이 가요~',
      timestamp: '2025-12-10T13:00:00Z',
    },
  ],
  'chat-11': [
    {
      id: 'msg-36',
      roomId: 'chat-11',
      senderId: 'user-1',
      senderName: '아미팬',
      content: '발렌타인 데이 뉴진스 콘서트! 💕',
      timestamp: '2025-12-13T14:00:00Z',
    },
    {
      id: 'msg-37',
      roomId: 'chat-11',
      senderId: 'user-23',
      senderName: '버니즈',
      content: '너무 설레요! 뉴진스 첫 콘서트예요',
      timestamp: '2025-12-13T14:30:00Z',
    },
    {
      id: 'msg-38',
      roomId: 'chat-11',
      senderId: 'user-1',
      senderName: '아미팬',
      content: '잠실역에서 만날까요?',
      timestamp: '2025-12-13T15:00:00Z',
    },
    {
      id: 'msg-39',
      roomId: 'chat-11',
      senderId: 'user-23',
      senderName: '버니즈',
      content: '발렌타인 데이 콘서트 너무 설레요!',
      timestamp: '2025-12-13T15:20:00Z',
    },
  ],
  'chat-12': [
    {
      id: 'msg-40',
      roomId: 'chat-12',
      senderId: 'user-2',
      senderName: '방탄소녀단',
      content: '에스파 SYNK TOUR 같이 가요!',
      timestamp: '2025-12-14T15:00:00Z',
    },
    {
      id: 'msg-41',
      roomId: 'chat-12',
      senderId: 'user-25',
      senderName: '닝닝팬',
      content: '에스파 콘서트 기대돼요!',
      timestamp: '2025-12-14T15:30:00Z',
    },
    {
      id: 'msg-42',
      roomId: 'chat-12',
      senderId: 'user-2',
      senderName: '방탄소녀단',
      content: '잠실 콘서트 좌석 어디가 좋을까요?',
      timestamp: '2025-12-14T16:00:00Z',
    },
    {
      id: 'msg-43',
      roomId: 'chat-12',
      senderId: 'user-25',
      senderName: '닝닝팬',
      content: '잠실 콘서트 좌석 어디가 좋을까요?',
      timestamp: '2025-12-14T16:40:00Z',
    },
  ],
};

export const mockSeatSections: SeatSection[] = [
  { id: 'vip', name: 'VIP석', price: 200000, availableSeats: 50, totalSeats: 100, color: '#ff1744' },
  { id: 'r', name: 'R석', price: 150000, availableSeats: 200, totalSeats: 300, color: '#9c27b0' },
  { id: 's', name: 'S석', price: 120000, availableSeats: 400, totalSeats: 500, color: '#667eea' },
  { id: 'a', name: 'A석', price: 90000, availableSeats: 600, totalSeats: 800, color: '#4caf50' },
];

export const generateSeats = (sectionId: string, rows: string[], seatsPerRow: number): Seat[] => {
  const section = mockSeatSections.find((s) => s.id === sectionId);
  const seats: Seat[] = [];

  rows.forEach((row) => {
    for (let i = 1; i <= seatsPerRow; i++) {
      const isAvailable = Math.random() > 0.3;
      seats.push({
        id: `${sectionId}-${row}${i}`,
        sectionId,
        row,
        number: i,
        price: section?.price || 0,
        status: isAvailable ? 'available' : 'sold',
      });
    }
  });

  return seats;
};

// Party Applicants Data
export const mockPartyApplicants: Record<string, PartyApplicant[]> = {
  'party-1': [
    {
      id: 'applicant-1',
      partyId: 'party-1',
      userId: 'user-4',
      userName: '보라해',
      message: '저도 함께 가고 싶어요! 잘 부탁드립니다~',
      appliedAt: '2025-12-10T11:00:00Z',
      status: 'accepted',
    },
    {
      id: 'applicant-2',
      partyId: 'party-1',
      userId: 'user-16',
      userName: '아미러버',
      message: '서울역에서 출발하면 편할 것 같아요',
      appliedAt: '2025-12-10T12:00:00Z',
      status: 'pending',
    },
  ],
  'party-3': [
    {
      id: 'applicant-3',
      partyId: 'party-3',
      userId: 'user-1',
      userName: '아미팬',
      message: '블랙핑크 팬사인회 처음인데 같이 가도 될까요?',
      appliedAt: '2025-12-10T10:00:00Z',
      status: 'accepted',
    },
    {
      id: 'applicant-4',
      partyId: 'party-3',
      userId: 'user-5',
      userName: '핑크팬',
      message: '점심 같이 먹어요!',
      appliedAt: '2025-12-10T10:30:00Z',
      status: 'accepted',
    },
    {
      id: 'applicant-5',
      partyId: 'party-3',
      userId: 'user-17',
      userName: '블링크짱',
      message: '혹시 자리 남았나요?',
      appliedAt: '2025-12-10T13:00:00Z',
      status: 'pending',
    },
  ],
  'party-5': [
    {
      id: 'applicant-6',
      partyId: 'party-5',
      userId: 'user-18',
      userName: '제니팬',
      message: '신논현역까지 같이 가요',
      appliedAt: '2025-12-11T11:00:00Z',
      status: 'accepted',
    },
  ],
  'party-6': [
    {
      id: 'applicant-7',
      partyId: 'party-6',
      userId: 'user-19',
      userName: '민지팬',
      message: '음악방송 처음 가봐요!',
      appliedAt: '2025-12-11T09:00:00Z',
      status: 'pending',
    },
    {
      id: 'applicant-8',
      partyId: 'party-6',
      userId: 'user-20',
      userName: '하니사랑',
      message: '디지털미디어시티역에서 만나요',
      appliedAt: '2025-12-11T10:00:00Z',
      status: 'rejected',
    },
  ],
  'party-7': [
    {
      id: 'applicant-9',
      partyId: 'party-7',
      userId: 'user-21',
      userName: '혜인짱',
      message: '쇼케이스 기대돼요!',
      appliedAt: '2025-12-12T12:00:00Z',
      status: 'accepted',
    },
    {
      id: 'applicant-10',
      partyId: 'party-7',
      userId: 'user-22',
      userName: '다니엘팬',
      message: '함께 가요~',
      appliedAt: '2025-12-12T13:00:00Z',
      status: 'accepted',
    },
  ],
  'party-8': [
    {
      id: 'applicant-11',
      partyId: 'party-8',
      userId: 'user-23',
      userName: '버니즈',
      message: '발렌타인 데이 콘서트 너무 기대돼요',
      appliedAt: '2025-12-13T10:00:00Z',
      status: 'accepted',
    },
  ],
  'party-9': [
    {
      id: 'applicant-12',
      partyId: 'party-9',
      userId: 'user-24',
      userName: '윈터팬',
      message: 'aespa 뮤직뱅크 같이 봐요',
      appliedAt: '2025-12-12T11:00:00Z',
      status: 'accepted',
    },
  ],
  'party-11': [
    {
      id: 'applicant-13',
      partyId: 'party-11',
      userId: 'user-25',
      userName: '닝닝팬',
      message: '잠실 콘서트 가고 싶어요',
      appliedAt: '2025-12-14T10:00:00Z',
      status: 'pending',
    },
  ],
  'party-12': [
    {
      id: 'applicant-14',
      partyId: 'party-12',
      userId: 'user-26',
      userName: '에스쿱스팬',
      message: '세븐틴 팬사인회 같이 가요',
      appliedAt: '2025-12-13T11:00:00Z',
      status: 'accepted',
    },
  ],
  'party-13': [
    {
      id: 'applicant-15',
      partyId: 'party-13',
      userId: 'user-27',
      userName: '정한팬',
      message: 'SBS에서 만나요',
      appliedAt: '2025-12-14T09:00:00Z',
      status: 'accepted',
    },
    {
      id: 'applicant-16',
      partyId: 'party-13',
      userId: 'user-28',
      userName: '조슈아팬',
      message: '인기가요 출연 기대돼요',
      appliedAt: '2025-12-14T10:00:00Z',
      status: 'accepted',
    },
  ],
  'party-15': [
    {
      id: 'applicant-17',
      partyId: 'party-15',
      userId: 'user-29',
      userName: '디노팬',
      message: '콘서트 끝나고 영등포역 가요',
      appliedAt: '2025-12-15T11:00:00Z',
      status: 'accepted',
    },
  ],
  'party-16': [
    {
      id: 'applicant-18',
      partyId: 'party-16',
      userId: 'user-30',
      userName: '리노팬',
      message: '스키즈 팬미팅 가고 싶어요',
      appliedAt: '2025-12-15T12:00:00Z',
      status: 'pending',
    },
  ],
  'party-18': [
    {
      id: 'applicant-19',
      partyId: 'party-18',
      userId: 'user-31',
      userName: '아이엔팬',
      message: 'MANIAC TOUR 함께 가요!',
      appliedAt: '2025-12-16T11:00:00Z',
      status: 'accepted',
    },
  ],
  'party-19': [
    {
      id: 'applicant-20',
      partyId: 'party-19',
      userId: 'user-32',
      userName: '승민팬',
      message: '건대입구역까지 함께 가요',
      appliedAt: '2025-12-16T12:00:00Z',
      status: 'pending',
    },
  ],
};

// Notifications Data
export const mockNotifications: Notification[] = [
  {
    id: 1,
    type: 'schedule',
    title: '예정된 일정 알림',
    message: 'BTS WORLD TOUR 2025가 3일 후 시작됩니다.',
    time: '3일 전',
    createdAt: '2025-12-12T10:00:00Z',
    read: false,
    eventId: '1',
  },
  {
    id: 2,
    type: 'party_request',
    title: '파티 신청',
    message: '아미러버님이 "BTS 콘서트 같이 가실 분!"에 참가 신청했습니다.',
    time: '1시간 전',
    createdAt: '2025-12-10T12:00:00Z',
    read: false,
    partyId: 'party-1',
  },
  {
    id: 3,
    type: 'party_accepted',
    title: '파티 승인',
    message: '블링크님이 회원님의 "BLACKPINK 팬사인회 동행" 신청을 승인했습니다.',
    time: '2시간 전',
    createdAt: '2025-12-10T10:00:00Z',
    read: false,
    partyId: 'party-3',
  },
  {
    id: 4,
    type: 'chat_message',
    title: '새 메시지',
    message: '보라해님: 안녕하세요! 같이 가요~',
    time: '30분 전',
    createdAt: '2025-12-10T12:30:00Z',
    read: false,
    chatRoomId: 'chat-1',
    partyId: 'party-1',
  },
  {
    id: 5,
    type: 'party_rejected',
    title: '파티 거절',
    message: '토끼팬님이 회원님의 신청을 거절했습니다.',
    time: '3시간 전',
    createdAt: '2025-12-11T10:00:00Z',
    read: true,
    partyId: 'party-6',
  },
  {
    id: 6,
    type: 'booking_confirmed',
    title: '예매 확정',
    message: 'NewJeans 쇼케이스 예매가 확정되었습니다.',
    time: '1일 전',
    createdAt: '2025-12-09T14:00:00Z',
    read: true,
    eventId: '10',
  },
  {
    id: 7,
    type: 'schedule',
    title: '일정 알림',
    message: 'aespa WINTER 생일이 내일입니다.',
    time: '5시간 전',
    createdAt: '2025-12-31T19:00:00Z',
    read: false,
    eventId: '4',
  },
  {
    id: 8,
    type: 'party_request',
    title: '새 신청',
    message: '블링크짱님이 "BLACKPINK 팬사인회 동행"에 참가 신청했습니다.',
    time: '4시간 전',
    createdAt: '2025-12-10T13:00:00Z',
    read: false,
    partyId: 'party-3',
  },
  {
    id: 9,
    type: 'info',
    title: '서비스 공지',
    message: '12월 31일 시스템 점검이 예정되어 있습니다.',
    time: '2일 전',
    createdAt: '2025-12-08T10:00:00Z',
    read: true,
  },
  {
    id: 10,
    type: 'success',
    title: '파티 생성 완료',
    message: '"BTS 콘서트 같이 가실 분!" 파티가 성공적으로 생성되었습니다.',
    time: '3일 전',
    createdAt: '2025-12-10T10:00:00Z',
    read: true,
    partyId: 'party-1',
  },
  {
    id: 11,
    type: 'warning',
    title: '파티 인원 확인',
    message: '"SEVENTEEN WORLD TOUR 동행" 파티가 곧 마감됩니다.',
    time: '6시간 전',
    createdAt: '2025-12-15T03:00:00Z',
    read: false,
    partyId: 'party-14',
  },
  {
    id: 12,
    type: 'party_accepted',
    title: '파티 승인',
    message: '뉴진스짱님이 회원님의 신청을 승인했습니다.',
    time: '7시간 전',
    createdAt: '2025-12-12T12:00:00Z',
    read: false,
    partyId: 'party-7',
  },
  {
    id: 13,
    type: 'schedule',
    title: '일정 알림',
    message: 'SEVENTEEN 팬사인회가 5일 후 시작됩니다.',
    time: '1일 전',
    createdAt: '2025-12-10T10:00:00Z',
    read: true,
    eventId: '12',
  },
  {
    id: 14,
    type: 'chat_message',
    title: '새 메시지',
    message: '핑크팬님: 저는 파스타 어떨까요?',
    time: '8시간 전',
    createdAt: '2025-12-10T10:30:00Z',
    read: true,
    chatRoomId: 'chat-2',
    partyId: 'party-3',
  },
  {
    id: 15,
    type: 'party_request',
    title: '파티 신청',
    message: '승민팬님이 "Stray Kids MANIAC TOUR 귀가"에 참가 신청했습니다.',
    time: '2시간 전',
    createdAt: '2025-12-16T12:00:00Z',
    read: false,
    partyId: 'party-19',
  },
];
