/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/party/{partyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 파티 수정
         * @description 파티 정보를 수정합니다. 파티장만 수정할 수 있습니다.
         */
        put: operations["updateParty"];
        post?: never;
        /**
         * 파티 삭제
         * @description 파티를 삭제합니다. 파티장만 삭제할 수 있습니다.
         */
        delete: operations["deleteParty"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 새로운 사용자를 등록합니다.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me/profile-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 프로필 이미지 업로드
         * @description 사용자의 프로필 이미지를 업로드합니다.
         */
        post: operations["uploadProfileImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 파티 목록 조회
         * @description 파티 목록을 조회합니다. 페이징 처리됩니다.
         */
        get: operations["getParties"];
        put?: never;
        /**
         * 파티 생성
         * @description 새로운 파티를 생성합니다.
         */
        post: operations["createParty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party/{partyId}/application/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 파티 참가 신청
         * @description 파티에 참가 신청을 합니다.
         */
        post: operations["applyToParty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 갱신
         * @description httpOnly secure 쿠키에 담긴 refresh token으로 새로운 access token과 refresh token을 발급받습니다. 새 access token은 Authorization 헤더로, 새 refresh token은 httpOnly secure 쿠키로 전달됩니다.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 비밀번호 재설정 이메일 발송
         * @description 비밀번호 재설정을 위한 이메일을 발송합니다.
         */
        post: operations["sendPasswordResetEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 비밀번호 재설정
         * @description 이메일로 받은 토큰을 사용하여 비밀번호를 재설정합니다.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description Authorization 헤더의 access token과 쿠키의 refresh token을 무효화하고 로그아웃합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 이메일과 비밀번호로 로그인합니다. 성공 시 access token은 Authorization 헤더로, refresh token은 httpOnly secure 쿠키로 전달됩니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이메일 인증 확인
         * @description 발송된 인증 코드를 확인하여 이메일을 인증합니다.
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이메일 인증 코드 발송
         * @description 이메일 인증을 위한 인증 코드를 발송합니다.
         */
        post: operations["sendVerifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artist/{artistId}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 아티스트 팔로우
         * @description 사용자가 특정 아티스트를 팔로우합니다.
         */
        post: operations["followArtist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description 로그인한 사용자의 정보를 조회합니다.
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 내 정보 수정
         * @description 사용자의 닉네임, 프로필 이미지를 수정합니다.
         */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/api/v1/party/{partyId}/application/{applicationId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 파티 신청 거절
         * @description 파티 신청을 거절합니다. 파티장만 거절할 수 있습니다.
         */
        patch: operations["rejectApplication"];
        trace?: never;
    };
    "/api/v1/party/{partyId}/application/{applicationId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 파티 신청 승인
         * @description 파티 신청을 승인합니다. 파티장만 승인할 수 있습니다.
         */
        patch: operations["acceptApplication"];
        trace?: never;
    };
    "/api/v1/schedule/partyList": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 이벤트 선택 목록 조회
         * @description 사용자가 팔로우하는 아티스트들의 외부 행사 중 현재 시점부터 31일 이내의 일정만 조회합니다. (파티 생성용과 파티 목록 조회용 드롭다운 목록 제공)
         */
        get: operations["getEventListsSchedules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedule/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 캘린더 화면 통합 데이터 조회
         * @description 특정 년/월의 전체 일정(혹은 특정 아티스트 필터링)과 다가오는 일정을 한 번에 반환합니다. 프론트엔드에서 날짜별 필터링을 수행하여 상세 내용을 표시할 수 있습니다.
         */
        get: operations["getFollowingSchedules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/performance/{performanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 공연 상세 정보 조회
         * @description 특정 공연의 상세 정보를 조회합니다. 예매 가능한 날짜 목록과 회차 정보를 포함합니다.
         */
        get: operations["getPerformanceDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party/{partyId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 파티 확정 멤버 목록 조회
         * @description 파티에 확정된 멤버 목록을 조회합니다.
         */
        get: operations["getPartyMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party/{partyId}/application/applicants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 파티 신청자 목록 조회
         * @description 파티에 신청한 사람들의 목록을 조회합니다. 파티장만 조회할 수 있습니다.
         */
        get: operations["getApplicants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party/user/me/party/created": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 만든 파티 목록 조회
         * @description 내가 만든 파티 목록을 조회합니다. 페이징 처리됩니다.
         */
        get: operations["getMyCreatedParties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party/user/me/party/application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 신청한 파티 목록 조회
         * @description 내가 신청한 파티 목록을 조회합니다. 페이징 처리됩니다.
         */
        get: operations["getMyApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party/schedule/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 스케줄별 파티 목록 조회
         * @description 특정 스케줄에 해당하는 파티 목록을 조회합니다. 파티 타입과 교통수단으로 필터링할 수 있습니다. 페이징 처리됩니다.
         */
        get: operations["getPartiesBySchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 이메일 인증 상태 확인
         * @description 유저의 이메일 인증 상태를 조회합니다. Authorization 헤더의 access token이 필요합니다.
         */
        get: operations["getEmailStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 아티스트 조회
         * @description 등록된 전체 아티스트 목록을 조회합니다.
         */
        get: operations["getAllArtists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artist/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팔로우한 아티스트 조회
         * @description 사용자가 팔로우한 아티스트 목록을 조회합니다.
         */
        get: operations["getFollowingArtists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/party/{partyId}/application/{applicationId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 파티 참가 신청 취소
         * @description 파티 참가 신청을 취소합니다.
         */
        delete: operations["cancelApplication"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artist/{artistId}/unfollow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 아티스트 언팔로우
         * @description 사용자가 특정 아티스트 팔로우를 취소합니다.
         */
        delete: operations["unfollowArtist"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 파티 수정 요청 */
        UpdatePartyRequest: {
            /**
             * @description 파티 이름
             * @example 지민이 최애
             */
            partyName?: string;
            /**
             * @description 파티 설명
             * @example 같이 즐겁게 콘서트 가요!
             */
            description?: string;
            /**
             * @description 출발 위치
             * @example 강남역 3번출구
             */
            departureLocation?: string;
            /**
             * @description 도착 위치
             * @example 잠실종합운동장
             */
            arrivalLocation?: string;
            /**
             * @description 이동 수단
             * @enum {string}
             */
            transportType?: "TAXI" | "CARPOOL" | "SUBWAY" | "BUS" | "WALK";
            /**
             * Format: int32
             * @description 최대 인원
             * @example 4
             */
            maxMembers?: number;
            /**
             * @description 선호 성별
             * @enum {string}
             */
            preferredGender?: "MALE" | "FEMALE" | "ANY";
            /**
             * @description 선호 연령대
             * @enum {string}
             */
            preferredAge?: "TEEN" | "TWENTY" | "THIRTY" | "FORTY" | "FIFTY_PLUS" | "NONE";
        };
        UpdatePartyResponse: {
            /**
             * Format: int64
             * @description 파티 ID
             * @example 1
             */
            partyId?: number;
            /**
             * Format: int64
             * @description 파티장 ID
             * @example 1
             */
            leaderId?: number;
            /**
             * @description 상태
             * @example 수정 완료
             */
            status?: string;
        };
        /** @description 회원가입 요청 */
        UserSignupRequest: {
            email?: string;
            password?: string;
            nickname?: string;
            gender?: string;
            /** Format: date */
            birthDate?: string;
        };
        /** @description 회원가입 응답 */
        UserSignupResponse: {
            /** Format: int64 */
            userId?: number;
            email?: string;
            nickname?: string;
            /** Format: date */
            birthDate?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 프로필 이미지 업로드 응답 */
        UploadProfileImgResponse: {
            profileImageUrl?: string;
        };
        /** @description 파티 생성 요청 */
        CreatePartyRequest: {
            /**
             * Format: int64
             * @description 일정 ID
             * @example 123
             */
            scheduleId: number;
            /**
             * @description 파티 타입
             * @enum {string}
             */
            partyType: "LEAVE" | "ARRIVE";
            /**
             * @description 파티 이름
             * @example 지민이 최애
             */
            partyName: string;
            /**
             * @description 파티 설명
             * @example 같이 즐겁게 콘서트 가요!
             */
            description?: string;
            /**
             * @description 출발 위치
             * @example 강남역 3번출구
             */
            departureLocation: string;
            /**
             * @description 도착 위치
             * @example 잠실종합운동장
             */
            arrivalLocation: string;
            /**
             * @description 이동 수단
             * @enum {string}
             */
            transportType: "TAXI" | "CARPOOL" | "SUBWAY" | "BUS" | "WALK";
            /**
             * Format: int32
             * @description 최대 인원
             * @example 4
             */
            maxMembers: number;
            /**
             * @description 선호 성별
             * @enum {string}
             */
            preferredGender: "MALE" | "FEMALE" | "ANY";
            /**
             * @description 선호 연령대
             * @enum {string}
             */
            preferredAge: "TEEN" | "TWENTY" | "THIRTY" | "FORTY" | "FIFTY_PLUS" | "NONE";
        };
        CreatePartyResponse: {
            /**
             * Format: int64
             * @description 파티 ID
             * @example 1
             */
            partyId?: number;
            /**
             * Format: int64
             * @description 파티장 ID
             * @example 1
             */
            leaderId?: number;
            /**
             * @description 상태
             * @example 생성 완료
             */
            status?: string;
        };
        ApplyToPartyResponse: {
            /**
             * @description 신청자 닉네임
             * @example 이치로
             */
            applicantNickName?: string;
            /**
             * Format: int32
             * @description 신청자 나이
             * @example 23
             */
            applicantAge?: number;
            /**
             * @description 신청자 성별
             * @example 남성
             * @enum {string}
             */
            gender?: "MALE" | "FEMALE" | "ANY";
            /**
             * @description 파티 이름
             * @example BTS 공연
             */
            partyTitle?: string;
        };
        /** @description 비밀번호 재설정 이메일 발송 요청 */
        UserPasswordResetSendRequest: {
            /**
             * Format: email
             * @description 이메일
             * @example user@example.com
             */
            email: string;
        };
        /** @description 비밀번호 재설정 요청 */
        UserPasswordResetRequest: {
            /**
             * @description 비밀번호 재설정 토큰
             * @example reset-token-12345-test-reset-token
             */
            token: string;
            /**
             * @description 새 비밀번호
             * @example newPassword123
             */
            newPassword: string;
            /**
             * @description 새 비밀번호 확인
             * @example newPassword123
             */
            newPasswordConfirm: string;
        };
        /** @description 유저 로그인 요청 */
        UserLoginRequest: {
            /**
             * Format: email
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 비밀번호
             * @example password123
             */
            password: string;
        };
        /**
         * @description 유저 로그인 응답
         *
         *     **응답 정보:**
         *     - Response Body에는 유저 정보만 포함됩니다
         *     - access token은 Response Header의 Authorization에 'Bearer {token}' 형식으로 설정됩니다
         *     - refresh token은 httpOnly secure 쿠키로 자동 설정됩니다
         *     - 쿠키 이름: refreshToken
         */
        UserLoginResponse: {
            /**
             * Format: int64
             * @description 유저 ID
             * @example 1
             */
            userId?: number;
            /**
             * @description 닉네임
             * @example 홍길동
             */
            nickname?: string;
            /**
             * @description 이메일
             * @example user@example.com
             */
            email?: string;
            /**
             * @description 프로필 이미지 URL
             * @example https://example.com/profile.jpg
             */
            profileImage?: string;
            /**
             * @description 이메일 인증 여부
             * @example true
             */
            emailVerified?: boolean;
        };
        /** @description 이메일 인증 확인 요청 */
        VerifyEmailRequest: {
            /**
             * Format: email
             * @description 이메일
             * @example user@example.com
             */
            email: string;
            /**
             * @description 인증 코드
             * @example 123456
             */
            code: string;
        };
        /** @description 이메일 인증 확인 응답 */
        VerifyEmailResponse: {
            /**
             * @description 이메일
             * @example user@example.com
             */
            email?: string;
            /**
             * @description 이메일 인증 여부
             * @example true
             */
            emailVerified?: boolean;
        };
        /** @description 이메일 인증 코드 발송 요청 */
        VerifyEmailSendRequest: {
            /**
             * Format: email
             * @description 이메일
             * @example user@example.com
             */
            email: string;
        };
        ErrorBody: {
            code?: string;
            status?: string;
            message?: string;
        };
        ErrorResponse: {
            error?: components["schemas"]["ErrorBody"];
        };
        /** @description 사용자 정보 수정 요청 */
        UpdateProfileRequest: {
            nickname?: string;
            profileImage?: string;
        };
        /** @description 사용자 프로필 응답 */
        UserProfileResponse: {
            email?: string;
            nickname?: string;
            profileImage?: string;
            /** Format: int32 */
            level?: number;
            /** Format: int32 */
            age?: number;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "ANY";
        };
        RejectApplicationResponse: {
            /**
             * Format: int64
             * @description 신청자 ID
             * @example 1
             */
            applicantId?: number;
            /**
             * @description 파티 이름
             * @example BTS 공연
             */
            partyName?: string;
            /**
             * Format: int64
             * @description 채팅방 ID
             * @example 1
             */
            chatRoomId?: number;
        };
        AcceptApplicationResponse: {
            /**
             * Format: int64
             * @description 신청자 ID
             * @example 1
             */
            applicantId?: number;
            /**
             * @description 파티 이름
             * @example BTS 공연
             */
            partyTitle?: string;
            /**
             * Format: int64
             * @description 채팅방 ID
             * @example 1
             */
            chatRoomId?: number;
        };
        EventResponse: {
            /**
             * Format: int64
             * @description 일정 ID
             * @example 120
             */
            scheduleId?: number;
            /**
             * @description 일정 제목
             * @example 뮤직뱅크 출연
             */
            title?: string;
        };
        EventsListResponse: {
            events?: components["schemas"]["EventResponse"][];
        };
        FollowingSchedulesListResponse: {
            /** @description 캘린더에 표시할 월별 일정 목록 (상세 정보 포함) */
            monthlySchedules?: components["schemas"]["ScheduleResponse"][];
            /** @description 사이드바 등에 표시할 다가오는 일정 목록 */
            upcomingEvents?: components["schemas"]["UpcomingEventResponse"][];
        };
        ScheduleResponse: {
            /**
             * Format: int64
             * @description 일정 ID
             * @example 120
             */
            scheduleId?: number;
            /**
             * Format: int64
             * @description 아티스트 ID
             * @example 2
             */
            artistId?: number;
            /**
             * @description 아티스트 이름
             * @example NewJeans
             */
            artistName?: string;
            /**
             * @description 일정 제목
             * @example 뮤직뱅크 출연
             */
            title?: string;
            /**
             * @description 일정 카테고리
             * @example BROADCAST
             * @enum {string}
             */
            scheduleCategory?: "CONCERT" | "FAN_MEETING" | "BROADCAST" | "ONLINE_RELEASE" | "BIRTHDAY" | "FESTIVAL" | "AWARD_SHOW" | "ANNIVERSARY" | "FAN_SIGN" | "LIVE_STREAM" | "ETC";
            /**
             * Format: date-time
             * @description 일정 시작 시간
             * @example 2025-12-15T17:00:00
             */
            scheduleTime?: string;
            /**
             * Format: int64
             * @description 공연 ID (선택 사항)
             * @example null
             */
            performanceId?: number;
            /**
             * @description 예매처 또는 관련 링크 (없을 경우 null)
             * @example https://ticket.example.com/newjeans
             */
            link?: string;
            /**
             * @description 일정 장소 (선택 사항)
             * @example KBS 신관 공개홀
             */
            location?: string;
        };
        UpcomingEventResponse: {
            /**
             * Format: int64
             * @description 일정 ID
             * @example 205
             */
            scheduleId?: number;
            /**
             * @description 아티스트 이름
             * @example aespa
             */
            artistName?: string;
            /**
             * @description 일정 제목
             * @example aespa 미니 4집 팬사인회
             */
            title?: string;
            /**
             * @description 일정 카테고리
             * @example FAN_SIGN
             * @enum {string}
             */
            scheduleCategory?: "CONCERT" | "FAN_MEETING" | "BROADCAST" | "ONLINE_RELEASE" | "BIRTHDAY" | "FESTIVAL" | "AWARD_SHOW" | "ANNIVERSARY" | "FAN_SIGN" | "LIVE_STREAM" | "ETC";
            /**
             * Format: date-time
             * @description 일정 시작 시간
             * @example 2025-12-20T14:00:00
             */
            scheduleTime?: string;
            /**
             * Format: int64
             * @description 공연 ID (선택 사항)
             * @example null
             */
            performanceId?: number;
            /**
             * @description 신청/예매 링크 (선택 사항)
             * @example https://fansign.example.com/aespa
             */
            link?: string;
            /**
             * Format: int64
             * @description 일정까지 남은 일수 (D-Day)
             * @example 5
             */
            daysUntilEvent?: number;
            /**
             * @description 일정 장소 (선택 사항)
             * @example 코엑스 라이브플라자
             */
            location?: string;
        };
        /** @description 아티스트 정보 */
        ArtistInfo: {
            /** Format: int64 */
            artistId?: number;
            artistName?: string;
        };
        /** @description 공연 상세 정보 응답 */
        PerformanceDetailResponse: {
            /** Format: int64 */
            performanceId?: number;
            title?: string;
            posterImageUrl?: string;
            artist?: components["schemas"]["ArtistInfo"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** Format: int32 */
            runningTime?: number;
            performanceHall?: components["schemas"]["PerformanceHallInfo"];
            priceGrades?: components["schemas"]["PriceGradeInfo"][];
            /** Format: date-time */
            salesStartTime?: string;
            /** Format: date-time */
            salesEndTime?: string;
            bookingNotice?: string;
            availableDates?: string[];
            schedules?: components["schemas"]["PerformanceScheduleResponse"][];
            isBookingOpen?: boolean;
            /** Format: int64 */
            secondsUntilOpen?: number;
        };
        /** @description 공연장 정보 */
        PerformanceHallInfo: {
            /** Format: int64 */
            performanceHallId?: number;
            name?: string;
            address?: string;
            transportationInfo?: string;
        };
        /** @description 공연 회차 정보 */
        PerformanceScheduleResponse: {
            /** Format: int64 */
            scheduleId?: number;
            /** Format: date */
            performanceDate?: string;
            startTime?: string;
            /** Format: int32 */
            PerformanceNo?: number;
            status?: string;
        };
        /** @description 가격 등급 정보 */
        PriceGradeInfo: {
            /** Format: int64 */
            priceGradeId?: number;
            gradeName?: string;
            /** Format: int32 */
            price?: number;
        };
        /** @description 이벤트 정보 */
        Event: {
            /**
             * Format: int64
             * @description 이벤트 ID
             * @example 123
             */
            eventId?: number;
            /**
             * @description 이벤트 제목
             * @example BTS WORLD TOUR 2025
             */
            eventTitle?: string;
            /**
             * @description 장소명
             * @example 잠실종합운동장
             */
            venueName?: string;
        };
        /** @description 파티 목록 조회 응답 */
        GetPartiesResponse: {
            /** @description 파티 목록 */
            content?: components["schemas"]["PartyItem"][];
            /**
             * Format: int32
             * @description 전체 요소 수
             * @example 45
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description 전체 페이지 수
             * @example 3
             */
            totalPages?: number;
            /**
             * Format: int32
             * @description 현재 페이지 번호
             * @example 0
             */
            pageNumber?: number;
        };
        /** @description 파티장 정보 */
        Leader: {
            /**
             * Format: int64
             * @description 사용자 ID
             * @example 100
             */
            userId?: number;
            /**
             * @description 닉네임
             * @example 지민이 최애
             */
            nickname?: string;
            /**
             * Format: int32
             * @description 나이
             * @example 23
             */
            age?: number;
            /**
             * @description 성별
             * @enum {string}
             */
            gender?: "MALE" | "FEMALE" | "ANY";
            /**
             * @description 프로필 이미지 URL
             * @example https://example.com/profile.jpg
             */
            profileImage?: string;
        };
        /** @description 파티 상세 정보 */
        PartyInfo: {
            /**
             * @description 파티 타입
             * @enum {string}
             */
            partyType?: "LEAVE" | "ARRIVE";
            /**
             * @description 파티 이름
             * @example 지민이 최애
             */
            partyName?: string;
            /**
             * @description 출발 위치
             * @example 강남역
             */
            departureLocation?: string;
            /**
             * @description 도착 위치
             * @example 잠실종합운동장
             */
            arrivalLocation?: string;
            /**
             * @description 이동 수단
             * @enum {string}
             */
            transportType?: "TAXI" | "CARPOOL" | "SUBWAY" | "BUS" | "WALK";
            /**
             * Format: int32
             * @description 최대 인원
             * @example 4
             */
            maxMembers?: number;
            /**
             * Format: int32
             * @description 현재 인원
             * @example 2
             */
            currentMembers?: number;
            /**
             * @description 설명
             * @example 같이 즐겁게 콘서트 가요!
             */
            description?: string;
            /**
             * @description 파티 상태
             * @enum {string}
             */
            status?: "RECRUITING" | "CLOSED" | "COMPLETED" | "CANCELLED";
        };
        /** @description 파티 항목 */
        PartyItem: {
            /**
             * Format: int64
             * @description 파티 ID
             * @example 1
             */
            partyId?: number;
            /** @description 파티장 정보 */
            leader?: components["schemas"]["Leader"];
            /** @description 이벤트 정보 */
            event?: components["schemas"]["Event"];
            /** @description 파티 상세 정보 */
            partyInfo?: components["schemas"]["PartyInfo"];
            /**
             * @description 내 파티 여부
             * @example false
             */
            isMyParty?: boolean;
            /**
             * @description 신청 여부
             * @example false
             */
            isApplied?: boolean;
        };
        /** @description 파티 확정 멤버 목록 조회 응답 */
        GetPartyMembersResponse: {
            /**
             * Format: int64
             * @description 파티 ID
             * @example 1
             */
            partyId?: number;
            /** @description 멤버 목록 */
            members?: components["schemas"]["MemberInfo"][];
            /**
             * Format: int32
             * @description 총 멤버 수
             * @example 2
             */
            totalMembers?: number;
        };
        /** @description 멤버 정보 */
        MemberInfo: {
            /**
             * Format: int64
             * @description 멤버 ID
             * @example 1
             */
            memberId?: number;
            /**
             * Format: int64
             * @description 사용자 ID
             * @example 100
             */
            userId?: number;
            /**
             * @description 닉네임
             * @example 지민이 최애
             */
            nickname?: string;
            /**
             * @description 프로필 이미지 URL
             * @example https://example.com/profile.jpg
             */
            profileImage?: string;
            /**
             * @description 역할
             * @example 파티장
             * @enum {string}
             */
            role?: "파티장" | "멤버";
        };
        /** @description 신청자 상세 정보 */
        ApplicantInfo: {
            /**
             * Format: int64
             * @description 사용자 ID
             * @example 200
             */
            userId?: number;
            /**
             * @description 닉네임
             * @example 명란 최애
             */
            nickname?: string;
            /**
             * @description 프로필 이미지 URL
             * @example https://example.com/profile.jpg
             */
            profileImage?: string;
            /**
             * @description 성별
             * @enum {string}
             */
            gender?: "MALE" | "FEMALE" | "ANY";
            /**
             * Format: int32
             * @description 나이
             * @example 23
             */
            age?: number;
        };
        /** @description 신청자 정보 */
        ApplicationInfo: {
            /**
             * Format: int64
             * @description 신청 ID
             * @example 101
             */
            applicationId?: number;
            /** @description 신청자 정보 */
            applicant?: components["schemas"]["ApplicantInfo"];
            /**
             * @description 신청 상태
             * @enum {string}
             */
            status?: "PENDING" | "APPROVED" | "REJECTED";
        };
        /** @description 신청 요약 정보 */
        ApplicationSummary: {
            /**
             * Format: int32
             * @description 전체 신청 수
             * @example 5
             */
            totalApplications?: number;
            /**
             * Format: int32
             * @description 대기중인 신청 수
             * @example 3
             */
            pendingCount?: number;
            /**
             * Format: int32
             * @description 승인된 신청 수
             * @example 2
             */
            acceptedCount?: number;
            /**
             * Format: int32
             * @description 거절된 신청 수
             * @example 0
             */
            rejectedCount?: number;
        };
        /** @description 파티 신청자 목록 조회 응답 */
        GetApplicantsResponse: {
            /**
             * Format: int64
             * @description 파티 ID
             * @example 1
             */
            partyId?: number;
            /** @description 신청자 목록 */
            applications?: components["schemas"]["ApplicationInfo"][];
            /** @description 신청 요약 정보 */
            summary?: components["schemas"]["ApplicationSummary"];
        };
        /** @description 신청 통계 정보 */
        ApplicationStatistics: {
            /**
             * Format: int32
             * @description 대기중인 신청 수
             * @example 3
             */
            pendingApplicationsCount?: number;
            /**
             * Format: int32
             * @description 승인된 멤버 수
             * @example 2
             */
            acceptedMembersCount?: number;
            /**
             * Format: int32
             * @description 거절된 신청 수
             * @example 1
             */
            rejectedApplicationsCount?: number;
        };
        /** @description 생성한 파티 항목 */
        CreatedPartyItem: {
            /**
             * Format: int64
             * @description 파티 ID
             * @example 1
             */
            partyId?: number;
            /** @description 이벤트 정보 */
            event?: components["schemas"]["EventInfo"];
            /** @description 파티 상세 정보 */
            partyInfo?: components["schemas"]["PartyDetailInfo"];
            /** @description 신청 통계 정보 */
            statistics?: components["schemas"]["ApplicationStatistics"];
            /**
             * @description 파티 설명
             * @example 같이 즐겁게 콘서트 가요!
             */
            description?: string;
            /**
             * Format: int64
             * @description 채팅방 ID
             * @example 50
             */
            chatRoomId?: number;
            /**
             * Format: date-time
             * @description 파티 생성 일시
             * @example 2025-12-01T10:00:00
             */
            createdAt?: string;
        };
        /** @description 행사 정보 */
        EventInfo: {
            /**
             * Format: int64
             * @description 행사 ID
             * @example 123
             */
            eventId?: number;
            /**
             * @description 행사 제목
             * @example BTS WORLD TOUR 2025
             */
            eventTitle?: string;
            /**
             * @description 장소
             * @example 잠실종합운동장
             */
            venueName?: string;
            /**
             * Format: date-time
             * @description 행사 일시
             * @example 2025-12-15T19:00:00
             */
            eventDateTime?: string;
        };
        /** @description 내가 만든 파티 목록 조회 응답 */
        GetMyCreatedPartiesResponse: {
            /** @description 파티 목록 */
            content?: components["schemas"]["CreatedPartyItem"][];
            /**
             * Format: int32
             * @description 전체 요소 수
             * @example 1
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description 전체 페이지 수
             * @example 1
             */
            totalPages?: number;
            /**
             * Format: int32
             * @description 현재 페이지 번호
             * @example 0
             */
            pageNumber?: number;
        };
        /** @description 파티 상세 정보 */
        PartyDetailInfo: {
            /**
             * @description 파티 타입
             * @example 출발팟
             * @enum {string}
             */
            partyType?: "출발팟" | "복귀팟";
            /**
             * @description 출발 위치
             * @example 강남역
             */
            departureLocation?: string;
            /**
             * Format: int32
             * @description 현재 인원
             * @example 2
             */
            currentMembers?: number;
            /**
             * Format: int32
             * @description 최대 인원
             * @example 4
             */
            maxMembers?: number;
        };
        /** @description 신청 항목 */
        ApplicationItem: {
            /**
             * Format: int64
             * @description 신청 ID
             * @example 101
             */
            applicationId?: number;
            /** @description 파티 정보 */
            party?: components["schemas"]["PartyInfo"];
            /**
             * @description 신청 상태
             * @example 대기중
             * @enum {string}
             */
            status?: "대기중" | "승인" | "거절";
            /**
             * Format: int64
             * @description 채팅방 ID (승인된 경우)
             * @example 60
             */
            chatRoomId?: number;
        };
        /** @description 신청한 파티 목록 조회 응답 */
        GetMyApplicationsResponse: {
            /** @description 신청 목록 */
            content?: components["schemas"]["ApplicationItem"][];
            /**
             * Format: int32
             * @description 전체 요소 수
             * @example 2
             */
            totalElements?: number;
            /**
             * Format: int32
             * @description 전체 페이지 수
             * @example 1
             */
            totalPages?: number;
            /**
             * Format: int32
             * @description 현재 페이지 번호
             * @example 0
             */
            pageNumber?: number;
        };
        /** @description 이메일 인증 상태 응답 */
        EmailStatusResponse: {
            /**
             * Format: int64
             * @description 유저 ID
             * @example 1
             */
            userId?: number;
            /**
             * @description 이메일
             * @example user@example.com
             */
            email?: string;
            /**
             * @description 이메일 인증 여부
             * @example true
             */
            emailVerified?: boolean;
            /**
             * Format: date-time
             * @description 인증 완료 시간
             * @example 2024-01-01T12:00:00
             */
            verifiedAt?: string;
        };
        ArtistListResponse: {
            artists?: components["schemas"]["ArtistResponse"][];
        };
        ArtistResponse: {
            /** Format: int64 */
            artistId?: number;
            name?: string;
            imageUrl?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateParty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePartyRequest"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "partyId": 1,
                     *       "leaderId": 1,
                     *       "status": "수정 완료"
                     *     }
                     */
                    "application/json": components["schemas"]["UpdatePartyResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3413",
                     *       "message": "현재 인원보다 적게 최대 인원을 설정할 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3104",
                     *       "message": "파티장만 파티를 수정할 수 있습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 파티를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3001",
                     *       "message": "파티를 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    deleteParty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3105",
                     *       "message": "파티장만 파티를 삭제할 수 있습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 파티를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3001",
                     *       "message": "파티를 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSignupRequest"];
            };
        };
        responses: {
            /** @description 회원가입 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSignupResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 중복된 데이터 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "DUPLICATE_NICKNAME",
                     *         "status": "409",
                     *         "message": "이미 사용 중인 닉네임입니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    uploadProfileImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    profile_image: string;
                };
            };
        };
        responses: {
            /** @description 업로드 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadProfileImgResponse"];
                };
            };
            /** @description 잘못된 파일 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "BAD_REQUEST",
                     *         "status": "400",
                     *         "message": "잘못된 요청입니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UNAUTHORIZED",
                     *         "status": "401",
                     *         "message": "로그인이 필요합니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getParties: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPartiesResponse"];
                };
            };
        };
    };
    createParty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePartyRequest"];
            };
        };
        responses: {
            /** @description 생성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "partyId": 1,
                     *       "leaderId": 1,
                     *       "status": "생성 완료"
                     *     }
                     */
                    "application/json": components["schemas"]["CreatePartyResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "001",
                     *       "message": "잘못된 요청입니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 일정을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "4001",
                     *       "message": "일정을 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    applyToParty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 신청 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "nickname": "지민이최애",
                     *       "age": 25,
                     *       "gender": "FEMALE",
                     *       "partyName": "즐거운 콘서트 관람"
                     *     }
                     */
                    "application/json": components["schemas"]["ApplyToPartyResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 파티를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3001",
                     *       "message": "파티를 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Refresh Token (httpOnly secure 쿠키) */
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description 토큰 갱신 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 토큰 갱신 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sendPasswordResetEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPasswordResetSendRequest"];
            };
        };
        responses: {
            /** @description 이메일 발송 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "BAD_REQUEST",
                     *         "status": "400",
                     *         "message": "잘못된 요청입니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_NOT_FOUND",
                     *         "status": "404",
                     *         "message": "유저를 찾을 수 없습니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPasswordResetRequest"];
            };
        };
        responses: {
            /** @description 비밀번호 재설정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 만료된 토큰 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "EXPIRED_PASSWORD_RESET_TOKEN",
                     *         "status": "401",
                     *         "message": "만료된 비밀번호 재설정 토큰입니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 토큰을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "PASSWORD_RESET_TOKEN_NOT_FOUND",
                     *         "status": "404",
                     *         "message": "비밀번호 재설정 토큰을 찾을 수 없습니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                /** @description Refresh Token (httpOnly secure 쿠키) */
                refreshToken?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description 로그아웃 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UNAUTHORIZED",
                     *         "status": "401",
                     *         "message": "로그인이 필요합니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserLoginResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "BAD_REQUEST",
                     *         "status": "400",
                     *         "message": "잘못된 요청입니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 로그인 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_CREDENTIALS",
                     *         "status": "401",
                     *         "message": "이메일 또는 비밀번호가 올바르지 않습니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description 이메일 인증 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyEmailResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "INVALID_EMAIL_VERIFICATION_CODE",
                     *         "status": "400",
                     *         "message": "유효하지 않은 인증 코드입니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 만료된 인증 코드 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "EXPIRED_EMAIL_VERIFICATION_CODE",
                     *         "status": "401",
                     *         "message": "만료된 인증 코드입니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sendVerifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailSendRequest"];
            };
        };
        responses: {
            /** @description 인증 코드 발송 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_NOT_FOUND",
                     *         "status": "404",
                     *         "message": "유저를 찾을 수 없습니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 너무 많은 요청 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "EMAIL_VERIFICATION_LIMIT_EXCEEDED",
                     *         "status": "429",
                     *         "message": "인증 코드 발송 횟수를 초과했습니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    followArtist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artistId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 팔로우 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 인증되지 않은 사용자 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 아티스트를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 팔로우한 아티스트 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UNAUTHORIZED",
                     *         "status": "401",
                     *         "message": "로그인이 필요합니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 사용자를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_NOT_FOUND",
                     *         "status": "404",
                     *         "message": "유저를 찾을 수 없습니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "BAD_REQUEST",
                     *         "status": "400",
                     *         "message": "잘못된 요청입니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UNAUTHORIZED",
                     *         "status": "401",
                     *         "message": "로그인이 필요합니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 닉네임 중복 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "DUPLICATE_NICKNAME",
                     *         "status": "409",
                     *         "message": "이미 사용 중인 닉네임입니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    rejectApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
                applicationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 거절 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "applicantId": 2,
                     *       "partyName": "즐거운 콘서트 관람",
                     *       "chatRoomId": null
                     *     }
                     */
                    "application/json": components["schemas"]["RejectApplicationResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3206",
                     *       "message": "이미 처리된 신청입니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3102",
                     *       "message": "파티장만 이 작업을 수행할 수 있습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    acceptApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
                applicationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 승인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "applicantId": 2,
                     *       "partyName": "즐거운 콘서트 관람",
                     *       "chatRoomId": null
                     *     }
                     */
                    "application/json": components["schemas"]["AcceptApplicationResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3102",
                     *       "message": "파티장만 이 작업을 수행할 수 있습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getEventListsSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "events": [
                     *         {
                     *           "scheduleId": 120,
                     *           "title": "[BTS] WORLD TOUR 2026"
                     *         },
                     *         {
                     *           "scheduleId": 121,
                     *           "title": "[NewJeans] 미니 3집 발매 팬사인회"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["EventsListResponse"];
                };
            };
            /** @description 권한 없음 (유저 인증 실패 등) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "2001",
                     *         "status": "403",
                     *         "message": "인증에 실패했습니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 일정 조회 실패 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "4001",
                     *         "status": "404",
                     *         "message": "일정을 찾을 수 없습니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getFollowingSchedules: {
        parameters: {
            query: {
                year: number;
                month: number;
                /** @description 특정 아티스트만 보고 싶을 때 ID 전달 (없으면 전체 팔로우 아티스트) */
                artistId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "monthlySchedules": [
                     *         {
                     *           "scheduleId": 120,
                     *           "artistId": 1,
                     *           "artistName": "NewJeans",
                     *           "title": "뮤직뱅크 출연",
                     *           "scheduleCategory": "BROADCAST",
                     *           "scheduleTime": "2025-12-15T17:00:00",
                     *           "performanceId": null,
                     *           "link": null,
                     *           "location": "KBS 신관 공개홀"
                     *         },
                     *         {
                     *           "scheduleId": 121,
                     *           "artistId": 2,
                     *           "artistName": "BTS",
                     *           "title": "팬사인회",
                     *           "scheduleCategory": "FAN_SIGN",
                     *           "scheduleTime": "2025-12-20T19:00:00",
                     *           "performanceId": null,
                     *           "link": "https://ticket.example.com/bts",
                     *           "location": "코엑스"
                     *         }
                     *       ],
                     *       "upcomingEvents": [
                     *         {
                     *           "scheduleId": 205,
                     *           "artistName": "aespa",
                     *           "title": "미니 4집 발매 콘서트",
                     *           "scheduleCategory": "CONCERT",
                     *           "scheduleTime": "2025-12-25T18:00:00",
                     *           "performanceId": 501,
                     *           "link": "https://ticket.example.com/aespa",
                     *           "daysUntilEvent": 5,
                     *           "location": "고척 스카이돔"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["FollowingSchedulesListResponse"];
                };
            };
            /** @description 잘못된 입력 (예: 월 범위 초과) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "004",
                     *         "status": "400",
                     *         "message": "유효하지 않은 입력값입니다. (month는 1~12 사이여야 합니다)"
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 권한 없음 (팔로우하지 않은 아티스트 필터링 시도) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "2003",
                     *         "status": "403",
                     *         "message": "해당 아티스트를 팔로우하고 있지 않습니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getPerformanceDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 공연 ID */
                performanceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceDetailResponse"];
                };
            };
            /** @description 리소스를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getPartyMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPartyMembersResponse"];
                };
            };
            /** @description 파티를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3001",
                     *       "message": "파티를 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getApplicants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetApplicantsResponse"];
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3102",
                     *       "message": "파티장만 이 작업을 수행할 수 있습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 파티를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3001",
                     *       "message": "파티를 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getMyCreatedParties: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMyCreatedPartiesResponse"];
                };
            };
        };
    };
    getMyApplications: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMyApplicationsResponse"];
                };
            };
        };
    };
    getPartiesBySchedule: {
        parameters: {
            query?: {
                partyType?: "LEAVE" | "ARRIVE";
                transportType?: "TAXI" | "CARPOOL" | "SUBWAY" | "BUS" | "WALK";
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                scheduleId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPartiesResponse"];
                };
            };
            /** @description 스케줄을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "4001",
                     *       "message": "일정을 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getEmailStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailStatusResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UNAUTHORIZED",
                     *         "status": "401",
                     *         "message": "로그인이 필요합니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 유저를 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "USER_NOT_FOUND",
                     *         "status": "404",
                     *         "message": "유저를 찾을 수 없습니다."
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    getAllArtists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistListResponse"];
                };
            };
        };
    };
    getFollowingArtists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtistListResponse"];
                };
            };
            /** @description 인증되지 않은 사용자 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                partyId: number;
                applicationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 취소 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3209",
                     *       "message": "승인된 신청은 취소할 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 권한 없음 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3101",
                     *       "message": "파티에 접근할 권한이 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description 신청을 찾을 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "3201",
                     *       "message": "신청 내역을 찾을 수 없습니다."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
        };
    };
    unfollowArtist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artistId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 언팔로우 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 팔로우 상태가 아님 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 인증되지 않은 사용자 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
